### Site info:
title: MochaPenguin's Musings
tagline: MochaPenguin's Musings
author: MochaPenguin
email: mochapenguin@gmail.com
description: "My adventure through the world of technology." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "MochaPenguin, blog"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mochapenguin.github.io" # the base hostname & protocol for your site
locale: en_GB

### Personal info and site tools info:
twitter_username: mochapenguin
github_username:  mochapenguin
disqus_shortname: mochapenguin
favicon:     "/images/favicon.ico"
aboutme: Hope you find my blog useful. # these are shown on aboutme-sidebar.
aboutme_photo: https://goo.gl/8Nif4y # your photo.
google_analytics_key: UA-96394455-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr), Russian (ru), and Turkish (tr)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: MochaPenguin
        href: https://mochapenguin.blogspot.co.uk
        title: MochaPenguin's Musings
      - name:  Blogspot
        href: https://mochapenguin.blogspot.co.uk
        title: MochaPenguin's Musings


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
